POST https://myshop-project-ct484-ctu-default-rtdb.firebaseio.com/products.json
Content-Type: application/json

{
"creatorId": "kQPvNYuQmoZW83FKYRdv0FKNkRS2",
"description": "Prepare any meal you want.",
"imageUrl": "https://upload.wikimedia.org/.../1024px-Cast-Iron-Pan.jpg",
"price": 49.99,
"title": "A Pan"
}
